export const SET_PHOTOS = "SET_PHOTOS";
export const SET_PHOTOS_ERROR = "SET_PHOTOS_ERROR";
export const SET_PHOTOS_LOADING = "SET_PHOTOS_LOADING";
export const SET_ACITVE_ALBUM = "SET_ACITVE_ALBUM";
export const SET_PHOTOS_PAGE = "SET_PHOTOS_PAGE";
