export const SET_POSTS = "SET_POSTS";
export const SET_POSTS_ERROR = "SET_POSTS_ERROR";
export const SET_ACTIVE_POST = "SET_ACTIVE_POST";
export const SET_POSTS_LOADING = "SET_POSTS_LOADING";
export const SET_POSTS_PAGE = "SET_POSTS_PAGE";
