export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_SEARCH_DATA = "SET_SEARCH_DATA";
export const SET_SEARCH_ERROR = "SET_SEARCH_ERROR";
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
